# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'InAppBilling' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking'
  pod 'CargoBay'
  pod 'RMStore'
  # Pods for InAppBilling

end
